// This file is auto-generated by @hey-api/openapi-ts
import { type DefaultError, type UseMutationOptions, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  type Options,
  createTransaction,
  createTransactionCategory,
  getTransaction,
  getTransactionGategory,
} from '../sdk.gen';
import type {
  CreateTransactionCategoryData,
  CreateTransactionCategoryResponse,
  CreateTransactionData,
  CreateTransactionResponse,
  GetTransactionData,
  GetTransactionGategoryData,
  GetTransactionGategoryResponse,
  GetTransactionResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getTransactionQueryKey = (options: Options<GetTransactionData>) =>
  createQueryKey('getTransaction', options);

export const getTransactionOptions = (options: Options<GetTransactionData>) =>
  queryOptions<
    GetTransactionResponse,
    DefaultError,
    GetTransactionResponse,
    ReturnType<typeof getTransactionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTransaction({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTransactionQueryKey(options),
  });

export const createTransactionMutation = (
  options?: Partial<Options<CreateTransactionData>>,
): UseMutationOptions<CreateTransactionResponse, DefaultError, Options<CreateTransactionData>> => {
  const mutationOptions: UseMutationOptions<
    CreateTransactionResponse,
    DefaultError,
    Options<CreateTransactionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTransaction({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getTransactionGategoryQueryKey = (options: Options<GetTransactionGategoryData>) =>
  createQueryKey('getTransactionGategory', options);

export const getTransactionGategoryOptions = (options: Options<GetTransactionGategoryData>) =>
  queryOptions<
    GetTransactionGategoryResponse,
    DefaultError,
    GetTransactionGategoryResponse,
    ReturnType<typeof getTransactionGategoryQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTransactionGategory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTransactionGategoryQueryKey(options),
  });

export const createTransactionCategoryMutation = (
  options?: Partial<Options<CreateTransactionCategoryData>>,
): UseMutationOptions<
  CreateTransactionCategoryResponse,
  DefaultError,
  Options<CreateTransactionCategoryData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTransactionCategoryResponse,
    DefaultError,
    Options<CreateTransactionCategoryData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTransactionCategory({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
