// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  CreateTransactionCategoryData,
  CreateTransactionCategoryResponses,
  CreateTransactionData,
  CreateTransactionResponses,
  GetTransactionData,
  GetTransactionGategoryData,
  GetTransactionGategoryResponses,
  GetTransactionResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getTransaction = <ThrowOnError extends boolean = false>(
  options: Options<GetTransactionData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetTransactionResponses, unknown, ThrowOnError>({
    url: '/transactions/{id}',
    ...options,
  });

export const createTransaction = <ThrowOnError extends boolean = false>(
  options: Options<CreateTransactionData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateTransactionResponses, unknown, ThrowOnError>({
    url: '/transactions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getTransactionGategory = <ThrowOnError extends boolean = false>(
  options: Options<GetTransactionGategoryData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetTransactionGategoryResponses, unknown, ThrowOnError>({
    url: '/transaction-categories/{id}',
    ...options,
  });

export const createTransactionCategory = <ThrowOnError extends boolean = false>(
  options: Options<CreateTransactionCategoryData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateTransactionCategoryResponses, unknown, ThrowOnError>({
    url: '/transaction-categories',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
