// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api` | (string & {});
};

export type TransactionCategoryCreateInput = {
  userId: number;
  parentId: number;
  name: string;
};

export type GetTransactionGategoryData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/categories/{id}';
};

export type GetTransactionGategoryResponses = {
  /**
   * Ok
   */
  200: {
    userId: number;
    parentId: number;
    name: string;
    id: number;
  };
};

export type GetTransactionGategoryResponse =
  GetTransactionGategoryResponses[keyof GetTransactionGategoryResponses];

export type CreateTransactionCategoryData = {
  body: TransactionCategoryCreateInput;
  path?: never;
  query?: never;
  url: '/categories';
};

export type CreateTransactionCategoryResponses = {
  /**
   * Ok
   */
  200: {
    userId: number;
    parentId: number;
    name: string;
    id: number;
  };
};

export type CreateTransactionCategoryResponse =
  CreateTransactionCategoryResponses[keyof CreateTransactionCategoryResponses];
