// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api` | (string & {});
};

export type CreateTransactionRequest = {
  name: string;
  amount: number;
  transactionCategoryId?: number;
};

export type CreateCategoryRequest = {
  name: string;
  amount: number;
  neccessary?: boolean;
};

export type GetTransactionData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/transactions/{id}';
};

export type GetTransactionResponses = {
  /**
   * Ok
   */
  200: {
    userId: number;
    parentId: number;
    name: string;
    id: number;
  };
};

export type GetTransactionResponse = GetTransactionResponses[keyof GetTransactionResponses];

export type CreateTransactionData = {
  body: CreateTransactionRequest;
  path?: never;
  query?: never;
  url: '/transactions';
};

export type CreateTransactionResponses = {
  /**
   * Ok
   */
  200: {
    neccessary: boolean;
    transactionCategoryId: number;
    amount: number;
    userId: number;
    name: string;
    id: number;
  };
};

export type CreateTransactionResponse =
  CreateTransactionResponses[keyof CreateTransactionResponses];

export type GetTransactionGategoryData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/transaction-categories/{id}';
};

export type GetTransactionGategoryResponses = {
  /**
   * Ok
   */
  200: {
    userId: number;
    parentId: number;
    name: string;
    id: number;
  };
};

export type GetTransactionGategoryResponse =
  GetTransactionGategoryResponses[keyof GetTransactionGategoryResponses];

export type CreateTransactionCategoryData = {
  body: CreateCategoryRequest;
  path?: never;
  query?: never;
  url: '/transaction-categories';
};

export type CreateTransactionCategoryResponses = {
  /**
   * Ok
   */
  200: {
    userId: number;
    parentId: number;
    name: string;
    id: number;
  };
};

export type CreateTransactionCategoryResponse =
  CreateTransactionCategoryResponses[keyof CreateTransactionCategoryResponses];
